server:
    url: http://localhost:1337
    title: test
mysql:
    cnct: true
    host: 127.0.0.1
    port: 3306
    user: root
    pssw: ''
    dbts: whatsthat
port:
    local   : 1337
    public  : 8080
links:
    assets:
        private : /src/views/assets/
        public  : /assets/
    views: /src/views/